#!/bin/sh
#
# Author(s): Alvaro Saurin <alvaro.saurin@suse.com>
#
# Copyright (c) 2017 SUSE LINUX GmbH, Nuernberg, Germany.
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.
#

CAASPCTL="${BASH_SOURCE[0]}"
DIR="$( cd "$( dirname "$CAASPCTL" )" && pwd )"


#
ETC_HOSTS="/etc/hosts"

####################################################################

log()     { echo ">>> $1" ; }
log_sys() { log "$1" ; logger -t "caaspctl" "$1" ; }
warn()    { log "WARNING: $1" ; }
abort()   { log "FATAL: $1" ; exit 1 ; }

########################
# /etc/hosts management
########################

# get the timstamps from STDIN
get_timestamps() {
    grep _stamp | tr "'" " " | awk '{print $NF}' | sort
}

plot_events() {

}

plot_usage() {
    cat<<EOF
$(basename $CAASPCTL) usage: subcommands:

        events  plot the timestamp

EOF
}

########################
# main
########################

cmd="$1"
shift
[ -z "$cmd" ] && plot_usage && abort "no subcommand provided when invoking $(basename $CAASPCTL)"

case "$cmd" in
    events)
        plot_events "$name" "$ip"
        ;;

    *)
        plot_usage && abort "Unknown argument $1"
        ;;
esac

